# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Thu Dec 25 16:34:42 2025
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class ReleaseDialogBase(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ReleaseDialogBase.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetSize((325, -1))
        self.SetTitle("Select a Release")

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        match_count = wx.StaticText(self, wx.ID_ANY, "Matches Found: 0")
        sizer_1.Add(match_count, 0, 0, 0)

        self.release_selector = wx.ComboBox(self, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN | wx.CB_READONLY)
        sizer_1.Add(self.release_selector, 0, wx.ALL | wx.EXPAND, 5)

        grid_sizer_1 = wx.FlexGridSizer(6, 2, 5, 5)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self, wx.ID_ANY, "Year")
        grid_sizer_1.Add(label_2, 0, 0, 0)

        year_label = wx.StaticText(self, wx.ID_ANY, "")
        grid_sizer_1.Add(year_label, 0, wx.ALIGN_RIGHT, 0)

        label_3 = wx.StaticText(self, wx.ID_ANY, "Locale")
        grid_sizer_1.Add(label_3, 0, 0, 0)

        locale_label = wx.StaticText(self, wx.ID_ANY, "")
        grid_sizer_1.Add(locale_label, 0, wx.ALIGN_RIGHT, 0)

        label_4 = wx.StaticText(self, wx.ID_ANY, "Release Date")
        grid_sizer_1.Add(label_4, 0, 0, 0)

        date_label = wx.StaticText(self, wx.ID_ANY, "")
        grid_sizer_1.Add(date_label, 0, wx.ALIGN_RIGHT, 0)

        label_5 = wx.StaticText(self, wx.ID_ANY, "Slug")
        grid_sizer_1.Add(label_5, 0, 0, 0)

        slug_label = wx.StaticText(self, wx.ID_ANY, "")
        grid_sizer_1.Add(slug_label, 0, wx.ALIGN_RIGHT, 0)

        label_6 = wx.StaticText(self, wx.ID_ANY, "UPC")
        grid_sizer_1.Add(label_6, 0, 0, 0)

        upc_label = wx.StaticText(self, wx.ID_ANY, "")
        grid_sizer_1.Add(upc_label, 0, wx.ALIGN_RIGHT, 0)

        label_7 = wx.StaticText(self, wx.ID_ANY, "ASIN")
        grid_sizer_1.Add(label_7, 0, 0, 0)

        asin_label = wx.StaticText(self, wx.ID_ANY, "")
        grid_sizer_1.Add(asin_label, 0, wx.ALIGN_RIGHT, 0)

        sizer_2 = wx.StdDialogButtonSizer()
        sizer_1.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

        self.button_OK = wx.Button(self, wx.ID_OK, "")
        self.button_OK.SetDefault()
        sizer_2.AddButton(self.button_OK)

        self.button_CANCEL = wx.Button(self, wx.ID_CANCEL, "")
        sizer_2.AddButton(self.button_CANCEL)

        sizer_2.Realize()

        self.SetSizer(sizer_1)

        self.SetAffirmativeId(self.button_OK.GetId())
        self.SetEscapeId(self.button_CANCEL.GetId())

        self.Layout()

        self.Bind(wx.EVT_CLOSE, self.release_selected)
        # end wxGlade

    def release_selected(self, event):  # wxGlade: ReleaseDialogBase.<event_handler>
        print("Event handler 'release_selected' not implemented!")
        event.Skip()

# end of class ReleaseDialogBase
