# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Thu Dec 25 16:34:42 2025
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class SettingsDialogBase(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SettingsDialogBase.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetTitle("Required Settings")

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)

        label_1 = wx.StaticText(self, wx.ID_ANY, "DiscDB INNER Data Folder")
        sizer_3.Add(label_1, 0, 0, 0)

        self.discDB_datafolder = wx.TextCtrl(self, wx.ID_ANY, "Required")
        sizer_3.Add(self.discDB_datafolder, 1, 0, 0)

        self.db_data_button = wx.Button(self, wx.ID_ANY, "Browse")
        sizer_3.Add(self.db_data_button, 0, 0, 0)

        label_2 = wx.StaticText(self, wx.ID_ANY, "Other settings can be found in settings.json")
        sizer_1.Add(label_2, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        sizer_2 = wx.StdDialogButtonSizer()
        sizer_1.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

        self.button_OK = wx.Button(self, wx.ID_OK, "")
        self.button_OK.SetDefault()
        sizer_2.AddButton(self.button_OK)

        self.button_CLOSE = wx.Button(self, wx.ID_CLOSE, "")
        sizer_2.AddButton(self.button_CLOSE)

        sizer_2.Realize()

        self.SetSizer(sizer_1)
        sizer_1.Fit(self)

        self.SetAffirmativeId(self.button_OK.GetId())
        self.SetEscapeId(self.button_CLOSE.GetId())

        self.Layout()

        self.db_data_button.Bind(wx.EVT_BUTTON, self.browse_db_path)
        # end wxGlade

    def browse_db_path(self, event):  # wxGlade: SettingsDialogBase.<event_handler>
        print("Event handler 'browse_db_path' not implemented!")
        event.Skip()

# end of class SettingsDialogBase
