# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Thu Dec 25 19:46:22 2025
#

import wx
# begin wxGlade: dependencies
import wx.grid
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class TVFrameBase(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: TVFrameBase.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((1015, 700))
        self.SetTitle("MKV_Rename")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        outer_sizer = wx.BoxSizer(wx.VERTICAL)

        series_lookup_sizer = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, "Series/Release Lookup"), wx.HORIZONTAL)
        outer_sizer.Add(series_lookup_sizer, 0, wx.EXPAND, 0)

        self.search_txt_ctrl = wx.TextCtrl(series_lookup_sizer.GetStaticBox(), wx.ID_ANY, "B09GTQFTHK")
        self.search_txt_ctrl.SetToolTip("Enter an ASIN, UPC, TheDiscDB.com URL, or keyword to search for the series or release.")
        series_lookup_sizer.Add(self.search_txt_ctrl, 1, 0, 0)

        self.LookupButton = wx.Button(series_lookup_sizer.GetStaticBox(), wx.ID_ANY, "Search")
        self.LookupButton.SetToolTip("Search the database for the series or release.\n")
        series_lookup_sizer.Add(self.LookupButton, 0, 0, 0)

        self.asin_radio = wx.RadioButton(series_lookup_sizer.GetStaticBox(), wx.ID_ANY, "ASIN", style=wx.RB_GROUP)
        self.asin_radio.SetToolTip("Lookup using the ASIN")
        series_lookup_sizer.Add(self.asin_radio, 0, 0, 0)

        self.upc_radio = wx.RadioButton(series_lookup_sizer.GetStaticBox(), wx.ID_ANY, "UPC")
        self.upc_radio.SetToolTip("Lookup the release by the UPC barcode number.")
        series_lookup_sizer.Add(self.upc_radio, 0, 0, 0)

        self.url_radio = wx.RadioButton(series_lookup_sizer.GetStaticBox(), wx.ID_ANY, "URL")
        self.url_radio.SetToolTip("Find the release on the TheDiscDB.com website and paste the URL to find the series data.")
        self.url_radio.Enable(False)
        series_lookup_sizer.Add(self.url_radio, 0, 0, 0)

        self.keyword_radio = wx.RadioButton(series_lookup_sizer.GetStaticBox(), wx.ID_ANY, "Keyword")
        self.keyword_radio.SetToolTip("Search for series by keyword")
        self.keyword_radio.Enable(False)
        series_lookup_sizer.Add(self.keyword_radio, 0, 0, 0)

        self.index_button = wx.Button(series_lookup_sizer.GetStaticBox(), wx.ID_ANY, "Rebuild Index")
        series_lookup_sizer.Add(self.index_button, 0, 0, 0)

        self.button = wx.Button(series_lookup_sizer.GetStaticBox(), wx.ID_ANY, "Browse")
        self.button.SetToolTip("Manually navigate to the release folder.")
        series_lookup_sizer.Add(self.button, 0, 0, 0)

        row2_sizer = wx.BoxSizer(wx.HORIZONTAL)
        outer_sizer.Add(row2_sizer, 0, wx.EXPAND, 0)

        sizer_4 = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, "DiscDB Disk"), wx.HORIZONTAL)
        row2_sizer.Add(sizer_4, 3, wx.EXPAND, 0)

        self.discDB_disk_combo = wx.ComboBox(sizer_4.GetStaticBox(), wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN | wx.CB_READONLY)
        self.discDB_disk_combo.SetToolTip("Select a disk from the release in the Disc DB\n")
        self.discDB_disk_combo.Enable(False)
        sizer_4.Add(self.discDB_disk_combo, 1, 0, 0)

        log_sizer = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, "MakeMKV Log"), wx.HORIZONTAL)
        row2_sizer.Add(log_sizer, 5, wx.EXPAND, 0)

        self.log_browse_button = wx.Button(log_sizer.GetStaticBox(), wx.ID_ANY, "Browse")
        self.log_browse_button.SetToolTip("Load the MakeMKV Log file")
        log_sizer.Add(self.log_browse_button, 0, 0, 0)

        self.makemkv_disk_combo = wx.ComboBox(log_sizer.GetStaticBox(), wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        self.makemkv_disk_combo.SetMinSize((111, 23))
        self.makemkv_disk_combo.Enable(False)
        log_sizer.Add(self.makemkv_disk_combo, 1, 0, 0)

        row2_sizer.Add((0, 0), 0, 0, 0)

        input_file_sizer = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, "Video Files"), wx.HORIZONTAL)
        outer_sizer.Add(input_file_sizer, 0, wx.EXPAND, 0)

        label_1 = wx.StaticText(input_file_sizer.GetStaticBox(), wx.ID_ANY, "Input folder")
        input_file_sizer.Add(label_1, 0, wx.LEFT | wx.RIGHT, 5)

        self.video_input_field = wx.TextCtrl(input_file_sizer.GetStaticBox(), wx.ID_ANY, "", style=wx.TE_PROCESS_ENTER)
        input_file_sizer.Add(self.video_input_field, 1, wx.LEFT | wx.RIGHT, 10)

        self.input_path_button = wx.Button(input_file_sizer.GetStaticBox(), wx.ID_ANY, "Browse")
        input_file_sizer.Add(self.input_path_button, 0, 0, 0)

        static_line_1 = wx.StaticLine(input_file_sizer.GetStaticBox(), wx.ID_ANY, style=wx.LI_VERTICAL)
        input_file_sizer.Add(static_line_1, 0, wx.EXPAND | wx.LEFT | wx.RIGHT, 10)

        label_2 = wx.StaticText(input_file_sizer.GetStaticBox(), wx.ID_ANY, "Output folder")
        input_file_sizer.Add(label_2, 0, 0, 0)

        self.video_output_field = wx.TextCtrl(input_file_sizer.GetStaticBox(), wx.ID_ANY, "")
        self.video_output_field.SetToolTip("Enter the location for the output files. A default can be set in the settings file.")
        input_file_sizer.Add(self.video_output_field, 1, 0, 0)

        self.output_browse_button = wx.Button(input_file_sizer.GetStaticBox(), wx.ID_ANY, "Browse")
        input_file_sizer.Add(self.output_browse_button, 0, 0, 0)

        options_sizer = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, "Options"), wx.HORIZONTAL)
        outer_sizer.Add(options_sizer, 0, wx.EXPAND, 0)

        self.add_suffix_cb = wx.CheckBox(options_sizer.GetStaticBox(), wx.ID_ANY, "Add Episode Name as Suffix")
        self.add_suffix_cb.Enable(False)
        options_sizer.Add(self.add_suffix_cb, 0, 0, 0)

        label_3 = wx.StaticText(options_sizer.GetStaticBox(), wx.ID_ANY, "Series Name/ File Suffix")
        label_3.Enable(False)
        options_sizer.Add(label_3, 0, 0, 0)

        self.prefix_field = wx.TextCtrl(options_sizer.GetStaticBox(), wx.ID_ANY, "")
        self.prefix_field.SetToolTip("Enter the text you want at the start of the filename e.g the \"Avatar the Last Airbender\"")
        options_sizer.Add(self.prefix_field, 1, 0, 0)

        action_sizer = wx.StaticBoxSizer(wx.StaticBox(self.panel_1, wx.ID_ANY, "Actions"), wx.HORIZONTAL)
        outer_sizer.Add(action_sizer, 0, wx.EXPAND, 0)

        self.copy_fn_button = wx.Button(action_sizer.GetStaticBox(), wx.ID_ANY, "Copy info from DiscDB")
        action_sizer.Add(self.copy_fn_button, 0, 0, 0)

        self.gen_fn_button = wx.Button(action_sizer.GetStaticBox(), wx.ID_ANY, "Generate Filenames")
        self.gen_fn_button.Enable(False)
        action_sizer.Add(self.gen_fn_button, 0, 0, 0)

        self.rename_button = wx.Button(action_sizer.GetStaticBox(), wx.ID_ANY, "Rename!")
        action_sizer.Add(self.rename_button, 0, 0, 0)

        self.update_summary_button = wx.Button(action_sizer.GetStaticBox(), wx.ID_ANY, "Update Summary File")
        self.update_summary_button.Enable(False)
        action_sizer.Add(self.update_summary_button, 0, 0, 0)

        self.save_button = wx.Button(action_sizer.GetStaticBox(), wx.ID_ANY, "Save Status")
        self.save_button.SetToolTip("Save the current details to continue later.")
        self.save_button.Enable(False)
        action_sizer.Add(self.save_button, 0, 0, 0)

        self.load_button = wx.Button(action_sizer.GetStaticBox(), wx.ID_ANY, "Load Status")
        self.load_button.SetToolTip("Load previous paramaters and progress from a rename.")
        self.load_button.Enable(False)
        action_sizer.Add(self.load_button, 0, 0, 0)

        self.new_disk_button = wx.Button(action_sizer.GetStaticBox(), wx.ID_ANY, "New Disc Summary")
        self.new_disk_button.SetToolTip("Create a discXX-summary file for a new file, and launch a dialog ")
        self.new_disk_button.Enable(False)
        action_sizer.Add(self.new_disk_button, 0, 0, 0)

        self.import_buddy_button = wx.Button(action_sizer.GetStaticBox(), wx.ID_ANY, "Run ImportBuddy")
        self.import_buddy_button.SetToolTip("Run IMportBuddy")
        self.import_buddy_button.Enable(False)
        action_sizer.Add(self.import_buddy_button, 0, 0, 0)

        self.splitter_1 = wx.SplitterWindow(self.panel_1, wx.ID_ANY)
        self.splitter_1.SetMinimumPaneSize(20)
        self.splitter_1.SetSashGravity(0.7)
        outer_sizer.Add(self.splitter_1, 1, wx.EXPAND, 0)

        self.episode_grid = wx.grid.Grid(self.splitter_1, wx.ID_ANY)
        self.episode_grid.CreateGrid(10, 14)
        self.episode_grid.SetColLabelValue(0, "Ren")
        self.episode_grid.SetColSize(0, 40)
        self.episode_grid.SetColLabelValue(1, "Cpy")
        self.episode_grid.SetColSize(1, 40)
        self.episode_grid.SetColLabelValue(2, "Gen")
        self.episode_grid.SetColSize(2, 40)
        self.episode_grid.SetColLabelValue(3, "Source")
        self.episode_grid.SetColSize(3, 105)
        self.episode_grid.SetColLabelValue(4, "Current Filename")
        self.episode_grid.SetColSize(4, 250)
        self.episode_grid.SetColLabelValue(5, "Rename to:")
        self.episode_grid.SetColSize(5, 250)
        self.episode_grid.SetColLabelValue(6, "Season")
        self.episode_grid.SetColSize(6, 100)
        self.episode_grid.SetColLabelValue(7, "Type")
        self.episode_grid.SetColSize(7, 125)
        self.episode_grid.SetColLabelValue(8, "Ep #")
        self.episode_grid.SetColSize(8, 45)
        self.episode_grid.SetColLabelValue(9, "Sp #")
        self.episode_grid.SetColSize(9, 45)
        self.episode_grid.SetColLabelValue(10, "Content Name")
        self.episode_grid.SetColSize(10, 100)
        self.episode_grid.SetColLabelValue(11, "DiscDB Recommended")
        self.episode_grid.SetColSize(11, 225)
        self.episode_grid.SetColLabelValue(12, "Custom Suffix")
        self.episode_grid.SetColSize(12, 180)
        self.episode_grid.SetColLabelValue(13, "Summary File Description")
        self.episode_grid.SetColSize(13, 750)


        # Begin Custom Entry
        self.episode_grid.SetColFormatCustom(0, "bool")
        attr_checkbox = wx.grid.GridCellAttr()
        attr_checkbox.SetAlignment(wx.ALIGN_CENTER, wx.ALIGN_CENTER)
        attr_checkbox.SetRenderer(wx.grid.GridCellBoolRenderer())
        attr_checkbox.SetEditor(wx.grid.GridCellBoolEditor())
        for col in [3, 4]:
            attr_readonly = wx.grid.GridCellAttr()
            attr_readonly.SetReadOnly(True)
            self.episode_grid.SetColAttr(col, attr_readonly)

        attr_numeric = wx.grid.GridCellAttr()
        attr_numeric.SetEditor(wx.grid.GridCellNumberEditor())
        attr_numeric.SetAlignment(wx.ALIGN_CENTER, wx.ALIGN_CENTER)
        self.episode_grid.SetColAttr(8, attr_numeric)

        self.episode_grid.SetColAttr(0, attr_checkbox)
        tooltips = ["Check to rename the file when rename is clicked",
                    "Copy the filename from the suggestion in the TheDiscDB"]
        video_types = ['Episode', 'Extra', 'Deleted Scenes']
        type_editor = wx.grid.GridCellChoiceEditor(video_types) #, allow_free=False)
        attr = wx.grid.GridCellAttr()
        attr.SetEditor(type_editor)
        self.episode_grid.SetColAttr(7, attr)

        self.episode_grid.AutoSizeColumns()
        attr_center = wx.grid.GridCellAttr()
        attr_center.SetAlignment(wx.ALIGN_CENTER, wx.ALIGN_CENTER)
        self.episode_grid.SetColAttr(8, attr_center)
        # End custom entry
        # End mods to custom entry


        self.log_box = wx.TextCtrl(self.splitter_1, wx.ID_ANY, "", style=wx.TE_MULTILINE | wx.TE_READONLY)
        self.log_box.SetToolTip("Log Window")

        self.splitter_1.SplitHorizontally(self.episode_grid, self.log_box, 230)

        self.panel_1.SetSizer(outer_sizer)

        self.Layout()

        self.LookupButton.Bind(wx.EVT_BUTTON, self.search_series)
        self.index_button.Bind(wx.EVT_BUTTON, self.build_index)
        self.button.Bind(wx.EVT_BUTTON, self.browse_db)
        self.discDB_disk_combo.Bind(wx.EVT_COMBOBOX, self.discDB_disk_selected)
        self.log_browse_button.Bind(wx.EVT_BUTTON, self.browse_log)
        self.makemkv_disk_combo.Bind(wx.EVT_COMBOBOX, self.makemkv_disk_selected)
        self.video_input_field.Bind(wx.EVT_TEXT_ENTER, self.video_input_enter)
        self.input_path_button.Bind(wx.EVT_BUTTON, self.browse_input)
        self.output_browse_button.Bind(wx.EVT_BUTTON, self.browse_output)
        self.copy_fn_button.Bind(wx.EVT_BUTTON, self.copy_filenames)
        self.gen_fn_button.Bind(wx.EVT_BUTTON, self.generate_filenames)
        self.rename_button.Bind(wx.EVT_BUTTON, self.do_rename)
        self.update_summary_button.Bind(wx.EVT_BUTTON, self.update_summary)
        self.save_button.Bind(wx.EVT_BUTTON, self.save_status)
        self.load_button.Bind(wx.EVT_BUTTON, self.load_status)
        self.new_disk_button.Bind(wx.EVT_BUTTON, self.new_disk_summary)
        self.import_buddy_button.Bind(wx.EVT_BUTTON, self.run_importbuddy)
        # end wxGlade

    def search_series(self, event):  # wxGlade: TVFrameBase.<event_handler>
        print("Event handler 'search_series' not implemented!")
        event.Skip()

    def build_index(self, event):  # wxGlade: TVFrameBase.<event_handler>
        print("Event handler 'build_index' not implemented!")
        event.Skip()

    def browse_db(self, event):  # wxGlade: TVFrameBase.<event_handler>
        print("Event handler 'browse_db' not implemented!")
        event.Skip()

    def discDB_disk_selected(self, event):  # wxGlade: TVFrameBase.<event_handler>
        print("Event handler 'discDB_disk_selected' not implemented!")
        event.Skip()

    def browse_log(self, event):  # wxGlade: TVFrameBase.<event_handler>
        print("Event handler 'browse_log' not implemented!")
        event.Skip()

    def makemkv_disk_selected(self, event):  # wxGlade: TVFrameBase.<event_handler>
        print("Event handler 'makemkv_disk_selected' not implemented!")
        event.Skip()

    def video_input_enter(self, event):  # wxGlade: TVFrameBase.<event_handler>
        print("Event handler 'video_input_enter' not implemented!")
        event.Skip()

    def browse_input(self, event):  # wxGlade: TVFrameBase.<event_handler>
        print("Event handler 'browse_input' not implemented!")
        event.Skip()

    def browse_output(self, event):  # wxGlade: TVFrameBase.<event_handler>
        print("Event handler 'browse_output' not implemented!")
        event.Skip()

    def copy_filenames(self, event):  # wxGlade: TVFrameBase.<event_handler>
        print("Event handler 'copy_filenames' not implemented!")
        event.Skip()

    def generate_filenames(self, event):  # wxGlade: TVFrameBase.<event_handler>
        print("Event handler 'generate_filenames' not implemented!")
        event.Skip()

    def do_rename(self, event):  # wxGlade: TVFrameBase.<event_handler>
        print("Event handler 'do_rename' not implemented!")
        event.Skip()

    def update_summary(self, event):  # wxGlade: TVFrameBase.<event_handler>
        print("Event handler 'update_summary' not implemented!")
        event.Skip()

    def save_status(self, event):  # wxGlade: TVFrameBase.<event_handler>
        print("Event handler 'save_status' not implemented!")
        event.Skip()

    def load_status(self, event):  # wxGlade: TVFrameBase.<event_handler>
        print("Event handler 'load_status' not implemented!")
        event.Skip()

    def new_disk_summary(self, event):  # wxGlade: TVFrameBase.<event_handler>
        print("Event handler 'new_disk_summary' not implemented!")
        event.Skip()

    def run_importbuddy(self, event):  # wxGlade: TVFrameBase.<event_handler>
        print("Event handler 'run_importbuddy' not implemented!")
        event.Skip()

# end of class TVFrameBase
