#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Thu Dec 25 16:34:42 2025
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
from TVFrameBase import TVFrameBase


class TVRenameWindow(wx.App):
    def OnInit(self):
        self.frame = TVFrameBase(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class TVRenameWindow

if __name__ == "__main__":
    TVRenameBuddy = TVRenameWindow(0)
    TVRenameBuddy.MainLoop()
